ignore:
  - "*.md"

functions:
  clone:
    - command: subprocess.exec
      type: setup
      params:
        command: "mkdir -p mongodb-kubernetes-operator"
    - command: git.get_project
      type: setup
      params:
        directory: mongodb-kubernetes-operator

  go_test:
    - command: subprocess.exec
      type: test
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        command: "go test ./..."

  setup_operator_sdk:
    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        include_expansions_in_env:
          - workdir
        binary: scripts/ci/setup_operator_sdk.sh

  generate_k8s:
    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/generate_k8.sh

  setup_kubernetes_environment:
    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://storage.googleapis.com/kubernetes-release/release/v1.15.4/bin/linux/amd64/kubectl
          FILENAME: kubectl
          PERMISSIONS: "755"
          BINDIR: ${workdir}/bin

    - command: subprocess.exec
      type: setup
      params:
        working_dir: mongodb-kubernetes-operator/scripts/ci
        command: go run download.go
        env:
          URL: https://github.com/kubernetes-sigs/kind/releases/download/v0.7.0/kind-linux-amd64
          PERMISSIONS: "755"
          FILENAME: kind
          BINDIR: ${workdir}/bin

    - command: subprocess.exec
      type: setup
      params:
        add_to_path:
          - ${workdir}/bin
        working_dir: mongodb-kubernetes-operator
        binary: scripts/ci/create_kind_cluster.sh
        env:
          KUBECONFIG: ${workdir}/kube_config

tasks:
  - name: unit_tests
    commands:
      - func: clone
      - func: setup_operator_sdk
      - func: generate_k8s
      - func: go_test

  - name: e2e_test
    commands:
      - func: clone
      - func: setup_kubernetes_environment
        # deploy operator and run test

buildvariants:
  - name: go_unit_tests
    display_name: go_unit_tests
    run_on:
      - ubuntu1604-build
    stepback: false
    tasks:
      - name: unit_tests

  - name: e2e_tests
    display_name: e2e_tests
    run_on:
      - ubuntu1604-build
    stepback: false
    tasks:
      - name: e2e_test